### ISSUE TITLE
Manage running custom python script for pyclone to ctree conversion

### ISSUE THREAD

**Issue by giorgiagandolfi** [caravagnalab/nextflow_modules#15]
I set up a module that runs a custom python script (I decided to use python since the singularity image for pyclone-vi does not contain R). The python script obviously works when I give the absolute path to the script. 
Then I tried to follow the [guidelines](https://www.nextflow.io/docs/latest/module.html#module-binaries) to include custom scripts without specifying the ab path, in order to be `nf-core` compatible.
In particular I create the module folder like this:

```
modules/pyclonevi/
├── main.nf
└── resources
  └── usr
    └── bin
      └── pyclone_ctree.py
```
and then I add to the pipeline `main.nf` the following line:

`nextflow.enable.moduleBinaries = true`

Then I got this error:

```
N E X T F L O W  ~  version 21.10.6
Launching `/u/cdslab/ggandolfi/scratch/nextflow_modules/main.nf` [chaotic_torricelli] - revision: 59d54aeb3e
No such variable: moduleBinaries

 -- Check script '/u/cdslab/ggandolfi/scratch/nextflow_modules/main.nf' at line: 3 or see '.nextflow.log' file for more details
```

Probably I can be something related to nextflow version, but if anyone experiences this issue we can chat. The current version is:

```
[ggandolfi@login01 nextflow_modules]$ /orfeo/LTS/CDSLab/LT_storage/ncalonaci/nextflow/nextflow -v
nextflow version 21.10.6.5660
```
and the modules binaries are included in version 22.10.0

**Comment by nicola-calonaci** [comment]
Should this issue to be closed?
