### ISSUE TITLE
installation issue in Orfeo for freebayes depedencies (vcflib)

### ISSUE THREAD

**Issue by Stack7** [caravagnalab/nextflow_modules#6]
I am experiencing some installation troubles while I am installing freebayes into the cluster (ORFEO). Frebayees is useful to generate the input .vcf file to pass to WhatsHap. The problem rises when I tried to install some of the dependencies, in particular vcflib. 
The easiest way to dot his:
*conda install -c bioconda vcflib*
but of course, it fails. I am doing so inside a conda env I created. the error I have is the following:
ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::zlib-1.2.13-hd590300_5'.
Rolling back transaction: done
[Errno 2] No such file or directory: '/orfeo/opt/programs/intel/fedora37/conda/23.3.1/pkgs/zlib-1.2.13-hd590300_5/lib/libz.so'
()
I already tried to export the path of the library, but it didn't work. I try to update conda into the cluster since is not the latest version, but sadly nothing changed. I tried other way to install vcf, but all of them bring me at the same error or didn't work

**Comment by Katerina10-cloud** [comment]
May be you can try to use Singularity image Freebayees without installation it into cluster. I also experienced fist time similar issues and now I use the Singularity containers whenever possible.
